version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8081:80"
    depends_on:
      - mysql

  apache_php8:
    image: php:8.2-apache
    container_name: apache8
    restart: always
    volumes:
      - ./apache8:/var/www/html
    ports:
      - "8082:80"

  apache_php7:
    image: php:7.4-apache
    container_name: apache7
    restart: always
    volumes:
      - ./apache7:/var/www/html
    ports:
      - "8083:80"

volumes:
  mysql_data:

